version: '3'

services:
  backend:
    build:
      context: ./project
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:8000  # Adjust the API URL as per your setup

volumes:
  postgres_data:
